# Generated by Django 6.0.2 on 2026-02-10 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.URLField(help_text='Thumbnail image URL', max_length=500)),
                ('banner', models.URLField(blank=True, help_text='Large banner image URL (optional)', max_length=500)),
                ('url', models.URLField(help_text='Video stream URL (MP4, HLS, etc.)', max_length=500)),
                ('duration', models.CharField(blank=True, help_text="e.g., '2h 15m' or '45m'", max_length=50)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating out of 10', max_digits=3, null=True)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('cast', models.TextField(blank=True, help_text='Comma-separated list of actors')),
                ('language', models.CharField(blank=True, default='English', max_length=50)),
                ('quality', models.CharField(choices=[('SD', 'Standard Definition'), ('HD', 'High Definition'), ('FHD', 'Full HD'), ('4K', '4K Ultra HD')], default='HD', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on featured carousel')),
                ('is_live', models.BooleanField(default=False, help_text='Is this a live stream?')),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='streams.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Android device ID', max_length=255)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('watch_duration', models.IntegerField(default=0, help_text='Seconds watched')),
                ('completed', models.BooleanField(default=False)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='streams.stream')),
            ],
            options={
                'verbose_name_plural': 'Watch Histories',
                'ordering': ['-watched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['category', '-created_at'], name='streams_str_categor_2919d2_idx'),
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['is_featured', '-created_at'], name='streams_str_is_feat_7a43ca_idx'),
        ),
    ]
